// ============================================================================
// Attack-family bridge — the ONE place that maps between the three naming
// systems this pipeline uses, so the verifier's consistency gate and the
// collector's retrieval narrowing can never drift apart:
//
//   detector_ref  R-NET-BRUTEFORCE / R-NET-FLOOD / flow_rate_zscore / R-NET-BEACON
//   family        brute_force / flood / beacon        (the behavioural families)
//   technique     T1110 / T1498 / T1499 / T1071 / T1571  (what a claim names)
//
// DETECTOR_FAMILY mirrors soccore.DETECTOR_FAMILY and TECHNIQUE_FAMILY mirrors
// soccore.FAMILY_TECH. Only the three families the detectors can actually
// produce are here; a technique outside this map makes no family claim, so
// nothing can contradict it and nothing narrows on it.
// ============================================================================

/** Detector ref -> the behavioural family it is evidence OF. */
export const DETECTOR_FAMILY: Record<string, string> = {
  'R-NET-BRUTEFORCE': 'brute_force',
  'R-NET-FLOOD': 'flood',
  flow_rate_zscore: 'flood',
  'R-NET-BEACON': 'beacon',
};

/**
 * Technique -> the family a claim OF that technique belongs to. Includes the
 * nearest neighbours a hypothesis may legitimately reach: T1499 is the
 * endpoint-DoS sibling of T1498, T1571 the non-standard-port sibling of T1071.
 */
export const TECHNIQUE_FAMILY: Record<string, string> = {
  T1110: 'brute_force',
  T1498: 'flood',
  T1499: 'flood',
  T1071: 'beacon',
  T1571: 'beacon',
};

/** The families a set of technique ids implies (unknown ids contribute nothing). */
export function familiesOfTechniques(techniques: readonly string[]): Set<string> {
  const out = new Set<string>();
  for (const t of techniques) {
    const fam = TECHNIQUE_FAMILY[t];
    if (fam) out.add(fam);
  }
  return out;
}

// How an incident TITLE names its behavioural family. The title is the detection
// plane's own statement of what the incident is, and unlike
// `incidents.mitre_techniques` the report writer never overwrites it — so it is
// the safer anchor when deciding which family an incident's evidence should be
// drawn from.
//
// Matched on keywords rather than whole strings on purpose: the seed SQL on disk
// was generated by an earlier FAMILY_TITLE table ("Volumetric HTTP DDoS flood",
// "Ares botnet C2 beaconing") and does not equal the current one, so an exact
// match would silently fall through for the very incidents that matter. Ordered
// most-specific first — a title mentioning both would otherwise match the looser
// rule.
const TITLE_FAMILY_RULES: [RegExp, string][] = [
  [/brute[\s-]?force|credential/i, 'brute_force'],
  [/beacon|\bc2\b|command and control|botnet/i, 'beacon'],
  [/flood|\bddos\b|denial of service/i, 'flood'],
];

/**
 * The behavioural family an incident belongs to, read from its title. Returns
 * null for an unrecognised title — an annotation-derived incident (whose title
 * is the dataset's attack class) has no behavioural family to narrow on.
 */
export function familyFromTitle(title: string | null | undefined): string | null {
  if (!title) return null;
  for (const [pattern, family] of TITLE_FAMILY_RULES) {
    if (pattern.test(title)) return family;
  }
  return null;
}

/**
 * Does `technique` (as `claimed`) contradict the detectors behind it?
 *
 * Returns null (compatible) whenever there is nothing to contradict: the
 * technique makes no family claim, or the cited events carry no behavioural
 * signal at all. The second case matters — an annotation-only incident has only
 * `label` signals, and the dataset's label IS the claim, so the verifier must
 * not second-guess the dataset there.
 *
 * `behaviouralRefs` must already exclude `detector = 'label'` signals.
 */
export function techniqueConflict(technique: string, behaviouralRefs: string[]): string | null {
  const claimed = TECHNIQUE_FAMILY[technique];
  if (!claimed) return null;
  const present = [...new Set(behaviouralRefs.map((r) => DETECTOR_FAMILY[r]).filter(Boolean))];
  if (present.length === 0) return null;
  if (present.includes(claimed)) return null;
  return (
    `technique ${technique} (${claimed}) is contradicted by the detectors behind the ` +
    `cited evidence (${present.join(', ')}); the claim describes a different attack family ` +
    `than the flows it cites`
  );
}
