import { Link } from "@tanstack/react-router";
import { ArrowRight, ChevronDown, Fingerprint, Search } from "lucide-react";
import { useState } from "react";
import { snapshot } from "@/lib/soc-snapshot";
import { EmptyState, SectionTitle, Severity } from "./layout";
import { Button } from "@/components/ui/button";

export function Alerts() {
  const [search,setSearch] = useState("");
  const [expanded,setExpanded] = useState<string | null>(null);
  const rows = snapshot.alerts.filter((a)=>`${a.title} ${a.entity} ${a.detector}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-5 entrance"><div className="panel-surface flex flex-wrap items-center gap-5 p-5"><div className="flex size-11 items-center justify-center rounded-md border border-high/25 bg-high/10 text-high"><Fingerprint className="size-5"/></div><div className="flex-1"><div className="font-display text-lg font-semibold">{snapshot.metrics.alerts} correlated alerts</div><p className="mt-1 text-xs text-muted-foreground">Condensed from {snapshot.metrics.signals.toLocaleString()} raw detector signals in the committed CICIDS2017 seed.</p></div><div className="border-l border-border pl-5 font-mono text-lg text-primary">{(snapshot.metrics.signals/snapshot.metrics.alerts).toFixed(1)}×<div className="mt-1 text-[10px] text-faint">COMPRESSION</div></div></div>
  <section className="panel-surface overflow-hidden"><SectionTitle label="Alert queue" aside="Select a row to inspect detector contributions and source event references"/><div className="border-b border-border/70 px-5 py-3"><label className="flex max-w-sm items-center gap-2 rounded border border-border bg-background/50 px-3 py-2 text-muted-foreground"><Search className="size-4"/><input aria-label="Search alerts" value={search} onChange={(e)=>setSearch(e.target.value)} className="w-full bg-transparent text-xs text-foreground outline-none placeholder:text-faint" placeholder="Search alert, detector or entity"/></label></div>
    {rows.length === 0 ? <EmptyState title="No matching alerts" detail="Try another alert title, detector, or source entity."/> : <div className="divide-y divide-border/70">{rows.map((alert)=><div key={alert.id}><Button variant="ghost" onClick={()=>setExpanded(expanded===alert.id?null:alert.id)} aria-expanded={expanded===alert.id} className="soc-row h-auto w-full justify-start gap-4 rounded-none px-5 py-4 text-left hover:bg-panel2/40"><span className="size-2 shrink-0 rounded-full bg-high"/><div className="min-w-0 flex-1"><div className="whitespace-normal text-[13px] font-medium text-foreground">{alert.title}</div><div className="mt-1 truncate font-mono text-[10px] text-faint">{alert.detector} <span className="px-1">·</span> {alert.entity}</div></div><div className="hidden min-w-[85px] sm:block"><div className="font-mono text-xs text-foreground">{Math.round(alert.confidence*100)}%</div><div className="mt-1 text-[10px] text-faint">confidence</div></div><Severity value={alert.severity}/><ChevronDown className={`size-4 shrink-0 text-faint transition-transform ${expanded===alert.id?"rotate-180":""}`}/></Button>
    {expanded===alert.id && <div className="grid gap-5 border-t border-border/60 bg-background/35 px-5 py-5 md:grid-cols-2"><div><h3 className="mb-3 font-mono text-[10px] uppercase text-muted-foreground">Detector contributions</h3><div className="space-y-3">{Object.entries(alert.contributions).map(([name,value])=><div key={name}><div className="mb-1 flex justify-between gap-2 font-mono text-[10px]"><span className="truncate text-muted-foreground">{name}</span><span>{Math.round(value*100)}%</span></div><div className="h-1 bg-panel2"><div className="h-full bg-primary" style={{width:`${Math.min(100,value*100)}%`}}/></div></div>)}</div></div><div><h3 className="mb-3 font-mono text-[10px] uppercase text-muted-foreground">Source evidence</h3><p className="text-xs text-muted-foreground">{alert.correlations.toLocaleString()} correlated flows · entity <span className="font-mono text-foreground">{alert.entity}</span></p><div className="mt-3 flex flex-wrap gap-1.5">{alert.eventIds.map((id)=><span key={id} title={id} className="rounded border border-border bg-panel px-2 py-1 font-mono text-[10px] text-muted-foreground">{id.slice(0,8)}</span>)}</div><p className="mt-3 text-[11px] text-faint">Showing 8 source event IDs from the seed record.</p><Link to="/incidents/$incidentId" params={{incidentId:alert.incidentId}} className="mt-4 inline-flex items-center gap-1 text-xs text-primary hover:underline">Open related incident <ArrowRight className="size-3"/></Link></div></div>}</div>)}</div>}</section></div>;
}
