import { Link } from "@tanstack/react-router";
import { ArrowRight, Search, ShieldAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { fetchAttackKb, fetchIncidents, fetchVerifierCounts, type AttackKbRow, type IncidentRow } from "@/lib/live-api";
import { EmptyState, SectionTitle, Severity } from "./layout";

export function Incidents() {
  const [search,setSearch]=useState("");
  const [data,setData]=useState<IncidentRow[]|null>(null);
  const [kb,setKb]=useState<Map<string,AttackKbRow>>(new Map());
  const [counts,setCounts]=useState<Map<string,{supported:number;rejected:number}>>(new Map());
  const [error,setError]=useState<string|null>(null);
  useEffect(()=>{let live=true;(async()=>{try{const [incs,k]=await Promise.all([fetchIncidents(),fetchAttackKb()]);if(!live)return;setData(incs);setKb(k);const c=await fetchVerifierCounts(incs.map((i)=>i.incident_id));if(live)setCounts(c)}catch(e){if(live)setError(e instanceof Error?e.message:String(e))}})();return()=>{live=false}},[]);
  const rows=useMemo(()=>data?.filter((inc)=>`${inc.title??""} ${inc.code??""} ${(inc.mitre_techniques??[]).join(" ")}`.toLowerCase().includes(search.toLowerCase()))??[],[data,search]);
  if(error) return <div className="panel-surface"><EmptyState title="Incident data unavailable" detail={error}/></div>;
  if(!data) return <div className="panel-surface"><EmptyState title="Loading incidents" detail="Reading current incidents and verifier results from Supabase…"/></div>;
  const highest=data.length?Math.max(...data.map((i)=>i.risk_score)):0;
  const reportCount=data.filter((i)=>!!i.summary).length;
  return <div className="space-y-5 entrance"><div className="grid gap-3 sm:grid-cols-3"><div className="panel-surface p-5"><div className="font-mono text-[10px] uppercase text-faint">Total incidents</div><div className="mt-3 font-display text-3xl font-semibold">{data.length.toString().padStart(2,"0")}</div></div><div className="panel-surface p-5"><div className="font-mono text-[10px] uppercase text-faint">Highest risk</div><div className="mt-3 font-display text-3xl font-semibold text-crit">{Math.round(highest)}<span className="ml-1 text-xs text-faint">/ 100</span></div></div><div className="panel-surface p-5"><div className="font-mono text-[10px] uppercase text-faint">Investigation reports</div><div className="mt-3 font-display text-3xl font-semibold text-primary">{reportCount.toString().padStart(2,"0")}<span className="ml-2 text-xs font-normal text-faint">verified output</span></div></div></div>
    <section className="panel-surface overflow-hidden"><SectionTitle label="Incident queue" aside="Seed + uploaded incidents · newest first"/><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border/70 px-5 py-3"><label className="flex w-full max-w-sm items-center gap-2 rounded border border-border bg-background/50 px-3 py-2 text-muted-foreground"><Search className="size-4"/><input aria-label="Search incidents" value={search} onChange={(e)=>setSearch(e.target.value)} className="w-full bg-transparent text-xs text-foreground outline-none placeholder:text-faint" placeholder="Search incident, ID or MITRE technique"/></label><span className="font-mono text-[10px] text-faint">{rows.length} OF {data.length} RECORDS</span></div>
    {rows.length===0?<EmptyState title="No matching incidents" detail={data.length?"Try another incident title, ID, or MITRE technique.":"Upload a compatible flow CSV on Analyze to create an incident."}/>:<div className="overflow-x-auto"><table className="w-full min-w-[740px] text-left"><thead><tr className="border-b border-border bg-panel2/25 font-mono text-[10px] uppercase text-faint"><th className="px-5 py-3 font-medium">Incident / technique</th><th className="px-4 py-3 font-medium">Risk</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 font-medium">Verifier</th><th className="px-5 py-3 text-right font-medium">Record</th></tr></thead><tbody className="divide-y divide-border/60">{rows.map((inc)=>{const tech=inc.mitre_techniques?.[0];const attack=(tech&&kb.get(tech)?.name)||inc.title||"Incident";const c=counts.get(inc.incident_id);return <tr key={inc.incident_id} className="soc-row"><td className="px-5 py-4"><div className="flex items-center gap-3"><ShieldAlert className="size-4 shrink-0 text-high"/><div><Link to="/incidents/$incidentId" params={{incidentId:inc.incident_id}} className="text-[13px] font-medium hover:text-primary">{attack}</Link><div className="mt-1 font-mono text-[10px] text-faint">{inc.code??inc.incident_id.slice(0,8)} <span className="px-1">·</span> {tech??"—"}</div></div></div></td><td className="px-4 py-4"><div className="mono-number text-[13px] text-crit">{Math.round(inc.risk_score)} / 100</div><div className="mt-1 h-1 w-20 bg-panel2"><div className="h-full bg-crit" style={{width:`${Math.min(100,inc.risk_score)}%`}}/></div></td><td className="px-4 py-4"><Severity value={inc.status}/></td><td className="px-4 py-4 font-mono text-[11px] text-muted-foreground">{c?`${c.supported} supported · ${c.rejected} rejected`:inc.summary?"report ready":"not yet investigated"}</td><td className="px-5 py-4 text-right"><Link aria-label={`Open ${attack}`} to="/incidents/$incidentId" params={{incidentId:inc.incident_id}} className="inline-flex size-8 items-center justify-center rounded border border-border text-muted-foreground hover:border-primary/40 hover:text-primary"><ArrowRight className="size-4"/></Link></td></tr>})}</tbody></table></div>}</section></div>;
}
