import { Link } from "@tanstack/react-router";
import { ArrowRight, DatabaseZap, Fingerprint, Radio, ShieldAlert, Workflow } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { fetchAttackKb, fetchOverview, type AttackKbRow, type OverviewData } from "@/lib/live-api";
import { EmptyState, SectionTitle, Severity } from "./layout";

export function Overview() {
  const [data,setData]=useState<OverviewData|null>(null);
  const [kb,setKb]=useState<Map<string,AttackKbRow>>(new Map());
  const [error,setError]=useState<string|null>(null);
  useEffect(()=>{let live=true;Promise.all([fetchOverview(),fetchAttackKb()]).then(([d,k])=>{if(live){setData(d);setKb(k)}}).catch((e)=>live&&setError(e instanceof Error?e.message:String(e)));return()=>{live=false}},[]);
  const severityMax=useMemo(()=>Math.max(1,...(data?.severity.map((s)=>s.count)??[1])),[data]);
  const volumeMax=useMemo(()=>Math.max(1,...(data?.volume.map((v)=>v.count)??[1])),[data]);
  if(error) return <div className="panel-surface"><EmptyState title="Live data unavailable" detail={error}/></div>;
  if(!data) return <div className="panel-surface"><EmptyState title="Loading SOC data" detail="Reading current events, alerts, and incidents from Supabase…"/></div>;
  const metrics=[
    {label:"Normalized events",value:data.events.toLocaleString(),meta:"Stored flow records",icon:DatabaseZap,tone:"text-primary"},
    {label:"Detector signals",value:data.signals.toLocaleString(),meta:"Raw detector matches",icon:Radio,tone:"text-low"},
    {label:"Deduplicated alerts",value:String(data.alerts).padStart(2,"0"),meta:data.alerts?`${(data.signals/data.alerts).toFixed(1)}× signal compression`:"No alerts yet",icon:Fingerprint,tone:"text-high"},
    {label:"Correlated incidents",value:String(data.incidents).padStart(2,"0"),meta:"Current dataset only",icon:ShieldAlert,tone:"text-crit"},
  ];
  return <div className="space-y-5 entrance">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,meta,icon:Icon,tone})=><div key={label} className="panel-surface relative min-h-[137px] overflow-hidden p-5"><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-medium uppercase text-muted-foreground">{label}</span><Icon className={`size-4 ${tone}`} strokeWidth={1.7}/></div><div className={`mt-4 font-display text-[32px] font-semibold leading-none ${tone}`}>{value}</div><div className="mt-3 font-mono text-[10px] text-faint">{meta}</div></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-12"><div className="space-y-5 xl:col-span-8">
      <section className="panel-surface overflow-hidden"><SectionTitle label="Ingest activity" aside="Stored normalized events by hour"/><div className="px-5 pb-5 pt-6">{data.volume.length===0?<EmptyState title="No event volume yet" detail="Analyze a compatible flow CSV to populate the timeline."/>:<><div className="relative flex h-[228px] items-end gap-1.5 border-b border-border/70 pb-0.5 sm:gap-2.5">{data.volume.map((item,index)=><div key={item.hour} className="group relative flex h-full flex-1 items-end" title={`${item.hour}: ${item.count.toLocaleString()} events`}><div className={`soc-chart-bar w-full rounded-t-sm border-t ${index===data.volume.length-1?"border-primary bg-primary/60":"border-low/60 bg-low/35"}`} style={{height:`${Math.max(3,item.count/volumeMax*96)}%`}}/></div>)}</div><div className="mt-3 flex justify-between font-mono text-[10px] text-faint"><span>{data.volume[0]?.hour}</span><span>Events / hour</span><span>{data.volume.at(-1)?.hour}</span></div></>}</div></section>
      <section className="panel-surface overflow-hidden"><SectionTitle label="Priority incidents" aside="Live incident records · ordered by risk" href="/incidents"/><div className="divide-y divide-border/65">{data.priority.length===0?<EmptyState title="No incidents" detail="No current incident records were found."/>:data.priority.map((inc)=>{const tech=inc.mitre_techniques?.[0];const title=(tech&&kb.get(tech)?.name)||inc.title||"Incident";return <Link key={inc.incident_id} to="/incidents/$incidentId" params={{incidentId:inc.incident_id}} className="soc-row group flex flex-wrap items-center gap-3 px-5 py-4 sm:flex-nowrap"><span className="size-2 shrink-0 rounded-full bg-crit"/><div className="min-w-0 flex-1"><div className="text-[13px] font-medium transition-colors group-hover:text-primary">{title}</div><div className="mt-1 font-mono text-[10px] text-faint">{inc.code??inc.incident_id.slice(0,8)} <span className="px-1">·</span> MITRE {tech??"—"}</div></div><div className="ml-5 flex items-center gap-4 sm:ml-0"><span className="font-mono text-xs text-crit">RISK {Math.round(inc.risk_score)}</span><ArrowRight className="size-4 text-faint transition-transform group-hover:translate-x-1 group-hover:text-primary"/></div></Link>})}</div></section>
    </div><div className="space-y-5 xl:col-span-4">
      <section className="panel-surface overflow-hidden"><SectionTitle label="Severity distribution" aside="Current stored events"/><div className="space-y-5 p-5">{[...data.severity].sort((a,b)=>b.count-a.count).map(({name,count})=><div key={name}><div className="mb-2 flex items-center justify-between"><Severity value={name}/><span className="mono-number text-xs text-foreground">{count.toLocaleString()}</span></div><div className="h-1.5 overflow-hidden rounded-sm bg-panel2"><div className={`h-full rounded-sm ${name==="high"?"bg-high":name==="medium"?"bg-med":"bg-info"}`} style={{width:`${Math.max(2,count/severityMax*100)}%`}}/></div></div>)}</div></section>
      <section className="panel-surface overflow-hidden"><SectionTitle label="Source intelligence" aside="Observed log sources"/><div className="p-5">{data.sources.length===0?<p className="text-xs text-muted-foreground">No event sources yet.</p>:data.sources.map((source)=><div key={source.name} className="mb-4 last:mb-0"><div className="mb-2 flex items-center justify-between text-xs"><span className="capitalize">{source.name}</span><span className="mono-number text-muted-foreground">{source.count.toLocaleString()}</span></div><div className="h-1.5 bg-panel2"><div className="h-full bg-primary" style={{width:`${data.events?source.count/data.events*100:0}%`}}/></div></div>)}</div></section>
      <section className="panel-surface overflow-hidden"><SectionTitle label="Detection rules" aside="Configured detection plane"/><div className="flex items-center gap-4 p-5"><div className="flex size-12 items-center justify-center rounded-md border border-primary/20 bg-primary/10 text-primary"><Workflow className="size-5"/></div><div><div className="font-display text-xl font-semibold">{data.rules} <span className="text-sm font-normal text-muted-foreground">rules configured</span></div><p className="mt-1 font-mono text-[10px] text-faint">Network flow detection plane</p></div></div></section>
    </div></div>
    <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border py-3 font-mono text-[10px] text-faint"><span>DATA / SUPABASE · CURRENT DATASET</span><Link to="/alerts" className="flex items-center gap-1 text-primary hover:underline">Inspect detector evidence <ArrowRight className="size-3"/></Link></div>
  </div>;
}
