import { Link } from "@tanstack/react-router";
import { ArrowRight, DatabaseZap, Fingerprint, Radio, ShieldAlert, Workflow } from "lucide-react";
import { snapshot } from "@/lib/soc-snapshot";
import { SectionTitle, Severity } from "./layout";

const metrics = [
  { label:"Normalized events", value:snapshot.metrics.events.toLocaleString(), meta:"OCSF flow records", icon:DatabaseZap, tone:"text-primary" },
  { label:"Detector signals", value:snapshot.metrics.signals.toLocaleString(), meta:"Raw rule matches", icon:Radio, tone:"text-low" },
  { label:"Deduplicated alerts", value:String(snapshot.metrics.alerts).padStart(2,"0"), meta:`${(snapshot.metrics.signals / snapshot.metrics.alerts).toFixed(1)}× signal compression`, icon:Fingerprint, tone:"text-high" },
  { label:"Correlated incidents", value:String(snapshot.metrics.incidents).padStart(2,"0"), meta:"Ranked by risk score", icon:ShieldAlert, tone:"text-crit" },
];
const severityMax = Math.max(...snapshot.severity.map((s)=>s.count));
const volumeMax = Math.max(...snapshot.volume.map((v)=>v.count));
export function Overview() {
  return <div className="space-y-5 entrance">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label,value,meta,icon:Icon,tone })=><div key={label} className="panel-surface relative min-h-[137px] overflow-hidden p-5"><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-medium uppercase text-muted-foreground">{label}</span><Icon className={`size-4 ${tone}`} strokeWidth={1.7}/></div><div className={`mt-4 font-display text-[32px] font-semibold leading-none ${tone}`}>{value}</div><div className="mt-3 font-mono text-[10px] text-faint">{meta}</div></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-12">
      <div className="space-y-5 xl:col-span-8">
        <section className="panel-surface overflow-hidden"><SectionTitle label="Ingest activity" aside="Normalized events by hour · CICIDS2017 snapshot"/><div className="px-5 pb-5 pt-6"><div className="relative flex h-[228px] items-end gap-1.5 border-b border-border/70 bg-[linear-gradient(to_top,var(--border)_1px,transparent_1px)] bg-[length:100%_25%] pb-0.5 sm:gap-2.5">{snapshot.volume.map((item,index)=><div key={item.hour} className="group relative flex h-full flex-1 items-end" title={`${item.hour}: ${item.count.toLocaleString()} events`}><div className={`soc-chart-bar w-full rounded-t-sm border-t ${index === snapshot.volume.length-1 ? "border-primary bg-primary/60" : "border-low/60 bg-low/35"}`} style={{height:`${Math.max(3,item.count/volumeMax*96)}%`}}/><div className="pointer-events-none absolute bottom-full left-1/2 z-10 hidden -translate-x-1/2 whitespace-nowrap rounded border border-border bg-panel2 px-2 py-1 font-mono text-[10px] text-foreground shadow-lg group-hover:block">{item.hour} · {item.count.toLocaleString()}</div></div>)}</div><div className="mt-3 flex justify-between font-mono text-[10px] text-faint"><span>{snapshot.volume[0]?.hour}</span><span>Events / hour</span><span>{snapshot.volume.at(-1)?.hour}</span></div></div></section>
        <section className="panel-surface overflow-hidden"><SectionTitle label="Priority incidents" aside="Detection output · ordered by risk" href="/incidents"/><div className="divide-y divide-border/65">{snapshot.incidents.map((inc)=><Link key={inc.id} to="/incidents/$incidentId" params={{incidentId:inc.id}} className="soc-row group flex flex-wrap items-center gap-3 px-5 py-4 sm:flex-nowrap"><span className="size-2 shrink-0 rounded-full bg-crit"/><div className="min-w-0 flex-1"><div className="text-[13px] font-medium transition-colors group-hover:text-primary">{inc.title}</div><div className="mt-1 font-mono text-[10px] text-faint">{inc.code} <span className="px-1">·</span> MITRE {inc.mitre}</div></div><div className="ml-5 flex items-center gap-4 sm:ml-0"><span className="font-mono text-xs text-crit">RISK {inc.risk.toFixed(0)}</span><ArrowRight className="size-4 text-faint transition-transform group-hover:translate-x-1 group-hover:text-primary"/></div></Link>)}</div></section>
      </div>
      <div className="space-y-5 xl:col-span-4">
        <section className="panel-surface overflow-hidden"><SectionTitle label="Severity distribution" aside="Classified source events"/><div className="space-y-5 p-5">{[...snapshot.severity].sort((a,b)=>b.count-a.count).map(({name,count})=><div key={name}><div className="mb-2 flex items-center justify-between"><Severity value={name}/><span className="mono-number text-xs text-foreground">{count.toLocaleString()}</span></div><div className="h-1.5 overflow-hidden rounded-sm bg-panel2"><div className={`h-full rounded-sm ${name === "high" ? "bg-high" : name === "medium" ? "bg-med" : "bg-info"}`} style={{width:`${Math.max(2,count/severityMax*100)}%`}}/></div></div>)}</div></section>
        <section className="panel-surface overflow-hidden"><SectionTitle label="Source intelligence" aside="Observed log sources"/><div className="p-5">{snapshot.sources.map((source)=><div key={source.name}><div className="mb-3 flex items-center justify-between text-xs"><span className="flex items-center gap-2 capitalize"><span className="size-2 rounded-full bg-primary"/>{source.name} · CICFlowMeter</span><span className="mono-number text-muted-foreground">{source.count.toLocaleString()}</span></div><div className="h-1.5 bg-panel2"><div className="h-full bg-primary" style={{width:`${source.count/snapshot.metrics.events*100}%`}}/></div></div>)}<p className="mt-4 border-t border-border/70 pt-4 text-[11px] leading-relaxed text-muted-foreground">No cloud or endpoint sources are present in this seed dataset.</p></div></section>
        <section className="panel-surface overflow-hidden"><SectionTitle label="Detection rules" aside="Enabled in this seed"/><div className="flex items-center gap-4 p-5"><div className="flex size-12 items-center justify-center rounded-md border border-primary/20 bg-primary/10 text-primary"><Workflow className="size-5"/></div><div><div className="font-display text-xl font-semibold">{snapshot.metrics.rules} <span className="text-sm font-normal text-muted-foreground">rules configured</span></div><p className="mt-1 font-mono text-[10px] text-faint">Network flow detection plane</p></div></div></section>
      </div>
    </div>
    <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border py-3 font-mono text-[10px] text-faint"><span>DATASET / CICIDS2017 · COMMITTED SEED SNAPSHOT</span><Link to="/alerts" className="flex items-center gap-1 text-primary hover:underline">Inspect detector evidence <ArrowRight className="size-3"/></Link></div>
  </div>;
}
