import { Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowUpRight, CheckCircle2, CircleDashed, Fingerprint, Network, ShieldCheck, XCircle } from "lucide-react";
import { snapshot } from "@/lib/soc-snapshot";
import { EmptyState, SectionTitle, Severity } from "./layout";

export function Record({ incidentId }: { incidentId:string }) {
 const inc=snapshot.incidents.find((i)=>i.id===incidentId);
 if(!inc) return <div className="panel-surface"><EmptyState title="Incident not in this snapshot" detail="This preview contains only the three incident records committed to the project's CICIDS2017 seed."/><div className="pb-6 text-center"><Link className="text-xs text-primary hover:underline" to="/incidents">Return to incidents</Link></div></div>;
 const entities=snapshot.entities.filter((e)=>e.incidentId===inc.id);
 const alert=snapshot.alerts.find((a)=>a.incidentId===inc.id);
 return <div className="space-y-5 entrance"><Link to="/incidents" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-primary"><ArrowLeft className="size-4"/> Back to incident queue</Link>
 <div className="panel-surface overflow-hidden"><div className="border-b border-border/70 px-6 py-6"><div className="mb-3 flex flex-wrap items-center gap-2 font-mono text-[10px] uppercase text-faint"><span className="text-primary">Incident record</span><span>/</span><span>{inc.code}</span><span className="ml-auto">CICIDS2017 snapshot</span></div><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="max-w-3xl font-display text-2xl font-semibold leading-tight sm:text-[28px]">{inc.title}</h2><div className="mt-3 flex flex-wrap items-center gap-2"><span className="rounded border border-border bg-panel2/60 px-2 py-1 font-mono text-[10px] text-muted-foreground">MITRE ATT&CK · {inc.mitre}</span><Severity value={inc.status}/></div></div><div className="rounded-md border border-crit/30 bg-crit/10 px-4 py-3"><div className="font-mono text-[10px] uppercase text-crit">Risk score</div><div className="mt-1 font-display text-2xl font-semibold text-crit">{inc.risk}<span className="text-sm text-muted-foreground"> / 100</span></div></div></div></div><div className="grid divide-y divide-border/70 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="px-6 py-4"><div className="font-mono text-[10px] uppercase text-faint">Alert confidence</div><div className="mono-number mt-2 text-sm">{alert?`${(alert.confidence*100).toFixed(1)}%`:"—"}</div></div><div className="px-6 py-4"><div className="font-mono text-[10px] uppercase text-faint">Associated flows</div><div className="mono-number mt-2 text-sm">{alert?.correlations.toLocaleString()??"—"}</div></div><div className="px-6 py-4"><div className="font-mono text-[10px] uppercase text-faint">Verifier outcome</div><div className="mt-2 text-sm text-muted-foreground">Not investigated</div></div></div></div>
 <div className="grid gap-5 xl:grid-cols-12"><div className="space-y-5 xl:col-span-8"><section className="panel-surface overflow-hidden"><SectionTitle label="Investigation summary" aside="Evidence-grounded report status"/><div className="flex gap-3 p-5"><CircleDashed className="mt-0.5 size-5 shrink-0 text-high"/><div><h3 className="text-sm font-medium">No agent report in the seed record</h3><p className="mt-2 text-xs leading-relaxed text-muted-foreground">The detection pipeline identified this incident, but the committed dataset contains no agent runs, verified hypotheses, or report. No narrative has been generated here.</p></div></div></section><section className="panel-surface overflow-hidden"><SectionTitle label="Verifier verdicts" aside="Only evidence-supported claims should appear in a report"/><div className="grid gap-3 p-5 sm:grid-cols-2"><div className="flex items-center gap-3 rounded border border-border bg-panel2/35 p-4"><CheckCircle2 className="size-5 text-primary"/><div><div className="font-display text-lg font-semibold">0</div><div className="text-[11px] text-muted-foreground">Supported claims recorded</div></div></div><div className="flex items-center gap-3 rounded border border-border bg-panel2/35 p-4"><XCircle className="size-5 text-muted-foreground"/><div><div className="font-display text-lg font-semibold">0</div><div className="text-[11px] text-muted-foreground">Rejected claims recorded</div></div></div></div><p className="px-5 pb-5 text-xs text-muted-foreground">Verification has not run for this seed incident. Zero does not mean a claim was verified.</p></section><section className="panel-surface overflow-hidden"><SectionTitle label="Evidence references" aside="Source event IDs cited by the alert detector"/><div className="p-5"><p className="mb-4 text-xs text-muted-foreground">{alert?.correlations.toLocaleString()} correlated flows. These are detector references, not an agent's verified evidence findings.</p><div className="flex flex-wrap gap-2">{alert?.eventIds.map((id)=><span key={id} title={id} className="rounded border border-border bg-panel2/50 px-2.5 py-1.5 font-mono text-[10px] text-muted-foreground">{id}</span>)}</div></div></section></div>
 <div className="space-y-5 xl:col-span-4"><section className="panel-surface overflow-hidden"><SectionTitle label="Involved entities" aside="From correlated incident records"/><div className="divide-y divide-border/60 px-5">{entities.map((e)=><div key={`${e.role}-${e.value}`} className="flex items-start gap-3 py-3"><div className="flex size-8 shrink-0 items-center justify-center rounded border border-border bg-panel2 text-low"><Network className="size-4"/></div><div className="min-w-0"><div className="font-mono text-[10px] uppercase text-faint">{e.role} / {e.type}</div><div className="mt-1 break-all font-mono text-xs text-foreground">{e.value}</div></div></div>)}</div></section><section className="panel-surface overflow-hidden"><SectionTitle label="Detector signal" aside="Why this incident was surfaced"/><div className="p-5"><div className="flex items-center gap-2 font-mono text-xs text-high"><Fingerprint className="size-4"/>{alert?.detector??"No linked alert"}</div>{alert&&<div className="mt-5 space-y-3">{Object.entries(alert.contributions).map(([key,value])=><div key={key}><div className="mb-1 flex justify-between gap-2 font-mono text-[10px]"><span className="truncate text-muted-foreground">{key}</span><span>{Math.round(value*100)}%</span></div><div className="h-1 bg-panel2"><div className="h-full bg-primary" style={{width:`${Math.min(100,value*100)}%`}}/></div></div>)}</div>}<Link to="/alerts" className="mt-5 inline-flex items-center gap-1 text-xs text-primary hover:underline">Open alert queue <ArrowUpRight className="size-3"/></Link></div></section><section className="panel-surface overflow-hidden"><SectionTitle label="Agent audit" aside="Investigation trace"/><div className="flex gap-3 p-5"><ShieldCheck className="size-5 shrink-0 text-muted-foreground"/><p className="text-xs leading-relaxed text-muted-foreground">No agent executions, cited findings, or timeline entries are included in the repository's seed data. New locally analyzed batches can populate these records in the original application.</p></div></section></div></div></div>;
}
